version: '3'
services:
        api:
                image: sample-express-app
                build: .
                networks:
                        - backend
                ports:
                        - "9000:9000"
                volumes:
                        - ./:/usr/src/app
        web-cli:
                image: sample-express-app
                networks:
                        - backend
                command: sh

networks:
        backend:
                driver: bridge
